FROM ubuntu:14.10
MAINTAINER Guillaume Claret

RUN apt-get update && apt-get upgrade -y
RUN apt-get install -y gcc make git
RUN apt-get install -y curl m4 ruby
RUN apt-get install -y aspcud
RUN apt-get install -y g++ coinor-csdp
RUN apt-get install -y unzip liblablgtk-extras-ocaml-dev

# Bench user
RUN useradd --create-home bench
USER bench
ENV HOME /home/bench

# OCaml
WORKDIR /home/bench
RUN curl -L https://github.com/ocaml/ocaml/archive/<%= ocaml %>.tar.gz |tar -xz
WORKDIR ocaml-<%= ocaml %>
RUN ./configure && make world.opt
USER root
RUN make install
USER bench

<% camlp4 = {
  "4.02.0" => "4.02.0+2",
  "4.02.1" => "4.02.1+1"
} %>
<% if camlp4[ocaml] %>
# Camlp4
WORKDIR /home/bench
RUN curl -L https://github.com/ocaml/camlp4/archive/<%= camlp4[ocaml] %>.tar.gz |tar -xz
WORKDIR camlp4-<%= camlp4[ocaml].gsub("+", "-") %>
RUN ./configure && make all
USER root
RUN make install
USER bench
<% end %>

# OPAM
WORKDIR /home/bench
RUN curl -L https://github.com/ocaml/opam/archive/<%= opam %>.tar.gz |tar -xz
WORKDIR opam-<%= opam %>
RUN ./configure && make lib-ext && make
USER root
RUN make install
USER bench

# Initialize OPAM.
ENV OPAMJOBS <%= jobs %>

# Initialize Git
RUN git config --global user.email "bench@ben.ch" && git config --global user.name "Bench B. Bench"

# Get the HTML.
WORKDIR /home/bench
RUN curl -L https://github.com/coq-bench/make-html/archive/no-history.tar.gz |tar -xz
WORKDIR make-html-no-history
RUN git clone https://github.com/coq-bench/coq-bench.github.io html

# Add the private key to push to https://github.com/coq-bench/coq-bench.github.io
ADD id_rsa /home/bench/.ssh/
RUN chmod 400 /home/bench/.ssh/id_rsa

# Initialize the bench folder.
ADD . /home/bench/run
WORKDIR /home/bench/run
